/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import CRUDs.CRUDCervezas;
import CRUDs.CRUDVentas;
import java.awt.event.KeyEvent;

/**
 *
 * @author Hugo
 */
public class Cervezas extends javax.swing.JPanel {

    /**
     * Creates new form Cervezas
     */
    public Cervezas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCervezas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cerveza = new javax.swing.JLabel();
        txtCerveza = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        unidades = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btmAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(666, 551));
        setMinimumSize(new java.awt.Dimension(666, 551));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        display.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(display, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 650, 20));

        jTableCervezas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCervezas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableCervezasMousePressed(evt);
            }
        });
        jTableCervezas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableCervezasKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCervezas);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, 217));

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 15, 25));

        cerveza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cerveza.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cerveza.setText("Descripción de la cerveza:");
        jPanel1.add(cerveza);

        txtCerveza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCerveza);
        jPanel1.add(jLabel3);

        unidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unidades.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unidades.setText("Unidades:");
        jPanel1.add(unidades);

        txtCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtCantidad);
        jPanel1.add(jLabel2);

        btmAgregar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btmAgregar.setText("Agregar");
        btmAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btmAgregar);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 540, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        CRUDCervezas actualizar = new CRUDCervezas();
        actualizar.Actualizar();
        actualizar.MostrarRegistroCervezas();

        CRUDVentas actualizarComboBox = new CRUDVentas();
        actualizarComboBox.GenerarComboBox();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        CRUDCervezas borrar = new CRUDCervezas();
        borrar.Borrar();
        borrar.MostrarRegistroCervezas();
        
        
        CRUDVentas actualizarComboBox = new CRUDVentas();
        actualizarComboBox.GenerarComboBox();
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btmAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAgregarActionPerformed
        CRUDCervezas agregar = new CRUDCervezas();
        agregar.Guardar();
        agregar.MostrarRegistroCervezas();

        CRUDVentas actualizarComboBox = new CRUDVentas();
        actualizarComboBox.GenerarComboBox();

    }//GEN-LAST:event_btmAgregarActionPerformed

    private void jTableCervezasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCervezasMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCervezasMousePressed

    private void jTableCervezasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableCervezasKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN){
            CRUDCervezas mostrar = new CRUDCervezas();
            mostrar.Mostrar();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DELETE){
            CRUDCervezas borrar = new CRUDCervezas();
            borrar.Borrar();
            borrar.MostrarRegistroCervezas();
            CRUDVentas actualizarComboBox = new CRUDVentas();
            actualizarComboBox.GenerarComboBox();
        }
    }//GEN-LAST:event_jTableCervezasKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAgregar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JLabel cerveza;
    public static javax.swing.JLabel display;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableCervezas;
    public static javax.swing.JTextField txtCantidad;
    public static javax.swing.JTextField txtCerveza;
    private javax.swing.JLabel unidades;
    // End of variables declaration//GEN-END:variables
}
