/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package JFrames;

import CRUDs.CRUDBalance;
import CRUDs.CRUDGastos;
import Utilidades.ExportarExcel;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hugo
 */
public class Gastos extends javax.swing.JPanel {

    /** Creates new form Gastos */
    public Gastos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaGastos = new javax.swing.JTable();
        displayGastos = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        descripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        importe = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(666, 551));
        setMinimumSize(new java.awt.Dimension(666, 551));
        setPreferredSize(new java.awt.Dimension(708, 626));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaGastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaGastosMousePressed(evt);
            }
        });
        TablaGastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaGastosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TablaGastos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 228, 650, 190));

        displayGastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(displayGastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 660, 20));

        btnExportar.setText("Exportar tabla");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 15, 25));

        descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descripcion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descripcion.setText("Descripción :");
        jPanel1.add(descripcion);

        txtDescripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtDescripcion);
        jPanel1.add(jLabel3);

        importe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        importe.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        importe.setText("Importe:");
        jPanel1.add(importe);

        txtImporte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtImporte);
        jPanel1.add(jLabel4);

        fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fecha.setText("Fecha:");
        jPanel1.add(fecha);

        txtFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtFecha);
        jPanel1.add(jLabel6);

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAceptar.setText("Agregar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar);

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 610, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void TablaGastosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaGastosMousePressed
        CRUDGastos mostrar = new CRUDGastos();
        mostrar.Mostrar();
    }//GEN-LAST:event_TablaGastosMousePressed

    private void TablaGastosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaGastosKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN){
            CRUDGastos mostrar = new CRUDGastos();
            mostrar.Mostrar();
        }
        if(evt.getKeyCode()==KeyEvent.VK_DELETE){
            CRUDGastos borrar = new CRUDGastos();
            borrar.Borrar();
            borrar.MostrarRegistroGastos();
            CRUDBalance mostrar = new CRUDBalance();
            mostrar.ObtenerBalance();
        }
        
    }//GEN-LAST:event_TablaGastosKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        CRUDGastos actualizar = new CRUDGastos();
        actualizar.Actualizar();
        actualizar.MostrarRegistroGastos();
        
        CRUDBalance mostrar = new CRUDBalance();
        mostrar.ObtenerBalance();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        CRUDGastos borrar = new CRUDGastos();
        borrar.Borrar();
        borrar.MostrarRegistroGastos();
        
        CRUDBalance actualizar = new CRUDBalance();
        actualizar.ObtenerBalance();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        if (TablaGastos.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "No hay datos en la tabla para ser exportados");
        }

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de excel","xls");
        chooser.setFileFilter(filter);
        chooser.setDialogTitle("Guardar Archivo");
        chooser.setMultiSelectionEnabled(false);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showSaveDialog(null)==JFileChooser.APPROVE_OPTION){
            List<JTable> tb = new ArrayList<>();
            List<String> nom = new ArrayList<>();
            tb.add(TablaGastos);
            nom.add("Registro de Gastos");
            String file = chooser.getSelectedFile().toString().concat(".xls");

            try{
                ExportarExcel e = new ExportarExcel (new File(file), tb, nom);
                if (e.export()){
                    JOptionPane.showMessageDialog(null, "Los datos fueron exportados con éxito");
                }
            }
            catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Hubo un error");
            }

        }
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        CRUDGastos guardar = new CRUDGastos();
        guardar.Agregar();
        guardar.MostrarRegistroGastos();
        
        CRUDBalance actualizar = new CRUDBalance();
        actualizar.ObtenerBalance();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TablaGastos;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JLabel descripcion;
    public static javax.swing.JLabel displayGastos;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel importe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txtDescripcion;
    public static javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables

}
